# Generated by Django 5.2 on 2025-10-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(verbose_name='Статус код')),
                ('response_time', models.DurationField(verbose_name='Время ответа')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время проверки')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proverator_app.domain', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
