# Generated by Django 5.2 on 2025-10-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response_time',
            field=models.BigIntegerField(verbose_name='Время ответа'),
        ),
    ]
